#!/usr/bin/env python3
"""
Extrae la paleta de un logo y crea un archivo CSS con variables que sobreescriben :root.
Uso:
  python scripts/extract_palette.py --file "img/Virucha Salomón-Logo.jpg"

Instalación de dependencias:
  pip install pillow

Este script guarda `css/brand-vars.css` con variables CSS para tu proyecto.
"""
import os
import argparse
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSS_OUT = os.path.join(ROOT, 'css', 'brand-vars.css')

def rgb_to_hex(rgb):
    return '#{:02x}{:02x}{:02x}'.format(*rgb)

def get_top_colors(img_path, count=5, resize=200):
    img = Image.open(img_path).convert('RGBA')
    # Resize for speed
    img.thumbnail((resize, resize))
    # Remove fully transparent pixels
    pixels = [p for p in img.getdata() if p[3] > 20]
    if not pixels:
        pixels = list(img.getdata())
    # Reduce colors
    img_small = Image.new('RGBA', img.size)
    img_small.putdata(pixels)
    result = img_small.convert('P', palette=Image.ADAPTIVE, colors=count).convert('RGB')
    colors = result.getcolors()
    # colors is list of (count, (r,g,b))
    colors = sorted(colors, key=lambda x: x[0], reverse=True)
    palette = [c[1] for c in colors]
    return palette

def write_css_vars(vars_map):
    lines = ["/* Autogenerated brand variables - no editar a mano si se regenerará */", ":root {"]
    for k,v in vars_map.items():
        lines.append(f"  --{k}: {v};")
    lines.append("}")
    with open(CSS_OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines))
    print(f'Wrote {CSS_OUT}')

def guess_role_colors(palette):
    # palette is list of rgb tuples, ordered by frequency
    # We'll choose main colors: bg (dark), surface, accent, accent2, text
    # If palette already has dark or light, we map accordingly
    mapped = {}
    # Primary accent is the most saturated color (highest chroma)
    def chroma(rgb):
        r,g,b = rgb
        return max(r,g,b) - min(r,g,b)
    sorted_by_chroma = sorted(palette, key=lambda rgb: chroma(rgb), reverse=True)
    accent = sorted_by_chroma[0] if palette else (45, 212, 191)
    accent2 = sorted_by_chroma[1] if len(sorted_by_chroma) > 1 else accent

    # Choose background as the lightest color available in the logo palette, prefer true white if present
    lightest = max(palette, key=lambda rgb: (rgb[0]+rgb[1]+rgb[2])) if palette else (255,255,255)
    darkest = min(palette, key=lambda rgb: (rgb[0]+rgb[1]+rgb[2])) if palette else (15,23,36)

    # Choose surface as next-lightest color different than bg for contrast
    candidates = [p for p in palette if p != lightest]
    surface_choice = candidates[-1] if candidates else darkest

    mapped['bg'] = rgb_to_hex(lightest)
    mapped['surface'] = rgb_to_hex(surface_choice)
    # text: choose darkest color from palette to ensure legibility
    mapped['text'] = rgb_to_hex(darkest)
    # muted: choose a mid-tone in the palette
    if len(palette) >= 3:
        mapped['muted'] = rgb_to_hex(palette[len(palette)//2])
    else:
        mapped['muted'] = rgb_to_hex(darkest)
    mapped['accent'] = rgb_to_hex(accent)
    mapped['accent-2'] = rgb_to_hex(accent2)
    # Additional rgba-based variables for overlay and shadow (explicit rgba strings)
    def rgba_string(rgb, a=1):
        return f"rgba({rgb[0]},{rgb[1]},{rgb[2]},{a})"
    mapped['shadow-rgba'] = rgba_string(darkest, 0.08)
    mapped['surface-overlay'] = rgba_string(surface_choice, 0.92)
    mapped['modal-bg'] = rgba_string(darkest, 0.42)
    mapped['lightbox-bg'] = rgba_string(darkest, 0.6)
    mapped['btn-text'] = '#ffffff' if luminance(accent) < 130 else '#000000'
    return mapped

def main():
    parser = argparse.ArgumentParser(description='Extrae paleta de logo y genera css variables')
    parser.add_argument('--file', '-f', default='img/Virucha Salomón-Logo.jpg', help='Ruta del logo dentro del proyecto')
    args = parser.parse_args()
    logo_path = os.path.join(ROOT, args.file) if not os.path.isabs(args.file) else args.file
    if not os.path.exists(logo_path):
        print('Logo no encontrado:', logo_path)
        return
    palette = get_top_colors(logo_path)
    if not palette:
        print('No se pudo extraer paleta')
        return
    roles = guess_role_colors(palette)
    write_css_vars(roles)

if __name__ == '__main__':
    main()
